fawkesrobotics/fawkes

cfg/conf.d/mongodb.yaml
src/plugins/mongodb/mongodb_instance_config.cpp

Enable passing extra arguments to managed mongod instances.

MongoDB extra args for managed instances

---

.lgtm.yml

@timn: the C/C++ analysis results for `fawkes` are now available on LGTM.com: https://lgtm.com/projects/g/fawkesrobotics/fawkes/alerts/?mode=list&lang=cpp
The history of the code base is currently being analysed; results will appear as they come in.
As promised: here's the `lgtm.yml` file that makes it all work. Let me know if you have any questions/comments!

LGTM: create initial config for LGTM.com C/C++ analysis

---

src/plugins/robot-memory/robot_memory.cpp

Fixes to lock expiration handling.

Robot memory lock expiration

---

src/libs/config/net_handler.cpp
src/libs/config/yaml_node.h
src/libs/fvcams/firewire.cpp
src/libs/fvfilters/morphology/morphologicalfilter.h
src/libs/fvmodels/shape/circle.cpp
src/libs/fvutils/statistical/histogram_block.cpp
src/libs/logging/cache.cpp
src/libs/navgraph/constraints/constraint_repo.cpp
src/libs/protobuf_comm/client.cpp
src/libs/protobuf_comm/message_register.cpp
src/libs/protobuf_comm/server.cpp
src/plugins/bbsync/bbsync_plugin.cpp
src/plugins/colli/visualization_thread.cpp
src/plugins/laser/laser_plugin.cpp
src/plugins/openni/image_thread.cpp
src/plugins/pantilt/pantilt_plugin.cpp
src/plugins/roomba/roombajoy_thread.cpp
src/plugins/stn-generator/stn-generator_thread.cpp
src/plugins/xmlrpc/xmlrpc_thread.cpp
src/tools/plugin_generator/main.cpp

This fixes the remaining lgtm alerts.

Second chunk of fixes for lgtm results

---

src/libs/webview/rest_api.h
src/libs/webview/router.h
src/plugins/webview/plugin-rest-api/plugin-rest-api.cpp
src/plugins/webview/plugin-rest-api/plugin-rest-api.h

Make some parameters references. It seems [LGTM on Fawkes](https://lgtm.com/projects/g/fawkesrobotics/fawkes/) learned some new tricks. Those alerts just recently appeared, and rightfully so.

Webview performance improvements

---

src/plugins/eclipse-clp/externals/blackboard.cpp
src/plugins/eclipse-clp/externals/eclipse_path.cpp

There were just some oversights from bulk-fixing the code review warnings

eclipse-clp compile fixes

---

cfg/conf.d/clips-executive.yaml
src/plugins/clips-executive/clips/action-selection/temporal.clp
src/plugins/clips-executive/clips/execmon/temporal-missed-dispatch.clp
src/plugins/clips-executive/clips/execmon/temporal-over-duration.clp
src/plugins/clips-executive/clips/goal.clp
src/plugins/clips-executive/clips/plan.clp

This adds the concepts of warnings for goals and execution monitoring for temporal plans to detect missed dispatch times and exceeded durations. The goal reasoner can then use this information to decide whether to continue or abort a plan.

CX temporal execution monitoring

---

src/libs/interface/field_pointer.h
src/lua/skills/generic/fake_relgoto.lua
src/lua/skills/test.lua
src/plugins/xabsl/.gitignore
src/plugins/xabsl/Makefile
src/plugins/xabsl/XABSL-Soccer.patch
src/plugins/xabsl/engine_thread.cpp
src/plugins/xabsl/iface_field_wrapper.h
src/plugins/xabsl/skill_wrapper.cpp
src/plugins/xabsl/xabsl_tools.cpp

This adds some fixes so that the xabsl plugin can be built again. It is a proof-of-concept only at this point anyway, but it's still worth to keep it around for future reference.

XABSL plugin fixes

---

cfg/cedar/fawkes-model.clp
cfg/cedar/ros-model.clp
cfg/conf.d/cedar.yaml
src/plugins/Makefile
src/plugins/cedar/Makefile
src/plugins/cedar/cedar_plugin.cpp
src/plugins/cedar/cedar_thread.cpp
src/plugins/cedar/cedar_thread.h
src/plugins/cedar/clips/cedar-fawkes.clp
src/plugins/cedar/clips/cedar-ros.clp
src/plugins/cedar/clips/cedar.clp
src/plugins/cedar/clips/fawkes-battery.clp
src/plugins/cedar/clips/syscond.clp
src/plugins/cedar/plugin_director_thread.cpp
src/plugins/cedar/plugin_director_thread.h

This is an old rewrite of some even older code back from my days at SRI. It implements a system monitoring module. It compares the desired state of the system according to a model of the system (nodes, plugins, topics, connections, interfaces) with the actual state of Fawkes and ROS. On deviations, it raises warnings or errors. Eventually, system state is represented as "ok/green", "degraded/yellow", or "faulty/red". This can be used as an external input signal for system monitoring.
Capabilities not included in this version are fault trees (it only contains a basic one based on status conditions), and recovery actions. The Fawkes part lacks some functionality. The ROS part depends on the clips-ros plugin and is the more complete version.
Interestingly, CEDAR is an indirect predecessor of …

CEDAR: CLIPS-based Error Detection, Analysis, and Recovery

---

cfg/conf.d/plexil.yaml
cfg/plexil/external.xml
src/plugins/plexil/Makefile
src/plugins/plexil/blackboard_adapter.cpp
src/plugins/plexil/blackboard_adapter.h
src/plugins/plexil/plexil_thread.cpp
src/plugins/plexil/protobuf_adapter.cpp
src/plugins/plexil/protobuf_adapter.h
src/plugins/plexil/specs/test/plan.ple

This PR adds file locking during compilation, fixes a locking issue in the protobuf adapter, and adds a blackboard adapter for reading interface access.

Plexil improvements and blackboard access

---

src/plugins/clips-executive/clips/coordination-mutex.clp

This PR handles expirations of locks during renewal. This has been done by @morxa, who is currently on sick leave, hence I'm filing the PR to get this merge before our release.

Robot memory renewal of open lock

---

src/plugins/webview/frontend/package-lock.json
src/plugins/webview/frontend/package.json

Among other updates, this fixes an incompatibility issue of node-sass
with Node.js 10.

webview-frontend: update dependencies

---

etc/buildsys/root/check.mk
etc/buildsys/root/docs.mk
etc/docscripts/print_known_warnings.pl
etc/licscripts/find_invlic.pl

Make check only applies to files known to git

---

src/plugins/webview/frontend/package-lock.json
src/plugins/webview/frontend/package.json

Update all webview packages, also fix all vulnerabilities.
This includes an update of karma to a new major version. karma is used for testing. As we don't have any tests yet, this won't break anything.

Update webview frontend

---

.buildkite/pipeline.yml
src/libs/blackboard/blackboard.cpp
src/libs/core/assert_exception.h
src/libs/core/threading/thread_loop_listener.cpp
src/libs/fvclassifiers/border_shrinker.h
src/libs/fvmodels/shape/ht_lines.cpp
src/libs/fvmodels/shape/ht_lines.h
src/libs/syncpoint/tests/test_syncpoint.cpp
src/libs/webview/request.h
src/plugins/asp/aspect/clingo_access.cpp
src/plugins/perception/pcl-db/pcl_db_retrieve_pipeline.h

* Run buildkite builds with the [newly built Fedora 30 builder image](https://cloud.docker.com/u/fawkesrobotics/repository/docker/fawkesrobotics/fawkes-builder)
* Also run clang-format on the code base again, as clang-format on Fedora 30 behaves slightly differently (apparently, the new clang-format contains some bugfixes).
* Fix a number of documentation errors, found by a newer doxygen

Upgrade buildkite builds to Fedora 30

---

src/plugins/gologpp/execution_thread.cpp
src/plugins/gologpp/execution_thread.h
src/plugins/gologpp/exog_manager.cpp
src/plugins/gologpp/skiller_action_executor.h
src/plugins/gologpp/utils.cpp

These changes are required to build the gologpp plugin agains the latest golog++, where some aspects of the type system changed.

gologpp types api change

---

.buildkite/steps.d/20-webview-frontend.yml

Following up #262, also adapt the webview build.

buildkite: also switch webview build step to podman

---

src/libs/fvutils/adapters/cvmatadapter.cpp

This fixes the bugs in the color conversion introduced by the switch to the OpenCV C++ API.

Fix OpenCV to Firevision color conversions

---

src/plugins/clips-executive/clips/domain.clp
src/plugins/clips-pddl-parser/precondition_visitor.cpp

This PR mainly addresses a severe error in the satisfiability checks for atomic formulas + some minor refactoring.

Fixes for atomic formula satisfiability checks

---

.lgtm.yml
src/libs/core/threading/thread.cpp
src/plugins/mongodb_log/tools/ffmongodb_save_imgs.cpp
src/plugins/perception/pcl-db/pcl_db_pipeline.h
src/plugins/perception/tabletop-objects/tabletop_objects_thread.h

This adds small bits in order to compile within Fedora 35.
In general these are build issues related to deprecations.

Fixes required to build in Fedora 35

---

cfg/conf.d/bbsync.yaml
src/plugins/bbsync/Makefile
src/plugins/bbsync/interfaces/HeartbeatInterface.xml
src/plugins/bbsync/interfaces/Makefile
src/plugins/bbsync/sync_thread.cpp
src/plugins/bbsync/sync_thread.h

This PR is adding the interface to track the liveliness of the robotinos. This introduces the opportunity to react to losing the connection of a specific robotino.

BBSync: Added Interface to track the robotino liveliness

---

.buildkite/pipeline.yml
etc/buildsys/pcl.mk
src/libs/blackboard/internal/notifier.cpp
src/libs/syncpoint/syncpoint.cpp
src/libs/webview/access_log.cpp
src/plugins/katana/Makefile
src/plugins/mongodb/mongodb.mk
src/tools/laser_calibration/pitch_calibration.cpp

Fix build errors on Fedora 36 and adapt buildkite to use F36.

Switch to Fedora 36

---

src/plugins/webview/frontend/src/parts/clips-executive/components/goal-list.component.ts

Goal trees are now shown from left to right

Webview: Update Webview goals to more compact view

---

.buildkite/lint
.buildkite/pipeline.yml
.buildkite/test
cmake/lua.cmake

This is mainly relevant for our usage in fawkes-robotino.

more cmake fixes

---

src/plugins/ros2/irscan_thread.cpp
src/plugins/ros2/irscan_thread.h

The current behavior causes to many Publishes per minute and is causing the loop time to break down. I know only publish every Sensor hook loop.

ir_scan: performance fix
