src/plugins/robot-memory/event_trigger_manager.cpp
src/plugins/robot-memory/robot_memory.cpp

Add a missing try catch block to catch a possible mongodb exception. Also, if we get an exception while trying to lock, check the database again whether we still acquired the lock. We have seen a several cases where an exception was thrown, but the mutex was actually locked successfully. In that case, we should proceed as if no exception occurred.

robot memory: fix oplog exception

---

src/plugins/robot-memory/event_trigger_manager.cpp
src/plugins/robot-memory/robot_memory.cpp

The mongodb is not thread-safe and access must always be protected with a mutex. Add some missing mutex locks. This should protect every access to the mongodb client.
Also fix an issue with an apparently dead oplog cursor that would not be re-queried if an exception occurred.

Always protect mongodb client access with a mutex

---

.buildkite/pipeline.yml

Adds a small patch (seek-oss/github-merged-pr-buildkite-plugin#13) that ensures that the merge is performed non-interactive.

buildkite: update merged-pr build plugin to 0.0.7

---

src/plugins/clips-executive/clips/domain.clp

Switch any nowait action that is in the state `SENSED-EFFECTS-WAIT` to
`SENSED-EFFECTS-HOLD`.
This fixes a bug introduced by merge 1cf063f6b5442e93185019f5054dca1ce1ea4cba which would cause all nowait
actions to block and then eventually timeout.
This restores the behavior introduced with commit f486472151e334d8813b812c448b86b3dfb7ef98.

clips-executive: fix action timeout on nowait action

---

src/plugins/ros/navigator_thread.cpp
src/plugins/ros/navigator_thread.h

The NavigatorInterface allows to use a SetMaxSpeedMessage to set
translational speeds. Thus setting y and x velocities within the
navigator_thread is inconvenient. This should be handled by another ROS
node taking care of the appropriate situation.

ros-navigator: generalize trans vel for dynreconf

---

.buildkite/lint
.buildkite/pipeline.yml

This PR will
- add an exception for pushes to the master branch. We will rely on the Github branch protection for that branch.
- fix build annotations. The BUILDKITE env var was not passed through to the docker containers causing the check whether annotations are available to always fail and thus printing the error to the log only.
- improve gitlint annotations. Further similar improvements would be very welcome! See [this description](https://building.buildkite.com/control-layout-and-styling-in-build-annotations-c05913a2b436).

Master branch push exception and annotation fixes/improvements

---

src/plugins/laser-filter/filters/filter.cpp
src/plugins/laser-filter/filters/filter.h

We recently fixed a missing free reported by https://lgtm.com. Turns out
this was actually a false positive. However, we use a really strange
allocation scheme, where we allocate and free memory from the outside,
even though the member is directly tied to the lifetime of the Buffer
object.
Fix by moving memory management into Buffer where it belongs.
Confirmed in RCLL simulation to fix a crash on start. Fixes carologistics/fawkes-robotino#26.

laser-filter: fix double free in filter buffer

---

src/plugins/Makefile
src/plugins/asp/.gitignore
src/plugins/asp/Makefile
src/plugins/asp/asp.config
src/plugins/asp/asp.creator
src/plugins/asp/asp.files
src/plugins/asp/asp.includes
src/plugins/asp/asp_plugin.cpp
src/plugins/asp/asp_thread.cpp
src/plugins/asp/asp_thread.h
src/plugins/asp/aspect/Makefile
src/plugins/asp/aspect/asp.cpp
src/plugins/asp/aspect/asp.h
src/plugins/asp/aspect/asp_inifin.cpp
src/plugins/asp/aspect/asp_inifin.h
src/plugins/asp/aspect/clingo_access.cpp
src/plugins/asp/aspect/clingo_access.h
src/plugins/asp/aspect/clingo_control_manager.cpp
src/plugins/asp/aspect/clingo_control_manager.h
src/plugins/asp/aspect/clingo_manager.cpp
src/plugins/asp/aspect/clingo_manager.h
src/plugins/asp/aspect/clingo_manager_inifin.cpp
src/plugins/asp/aspect/clingo_manager_inifin.h
src/plugins/asp/clingo.mk

This provides the basic integration for the Answer Set Programming (ASP) solver [Clingo](https://github.com/potassco/clingo) (requires a version with [Clingo PR #127](https://github.com/potassco/clingo/pull/127) integrated on recent compilers).
This is the base system part of the paper published at [ICAPS 2018](https://www.aaai.org/ocs/index.php/ICAPS/ICAPS18/paper/view/17777). It has been modified from the original version in terms of commit style and some commits adapt the code style to Fawkes' and enable using a [package-installed Clingo version](https://copr.fedorainfracloud.org/coprs/timn/clingo/) (which is integrated into the [fawkes-builder](https://github.com/fawkesrobotics/docker-robotics/tree/master/fawkes-builder) image (for Fedora), and thus included into CI builds).

Merge Clingo ASP solver integration

---

src/plugins/laser/sick_tim55x_common_aqt.cpp

This was introduced in 3765f31 when fixing a Codacy error. This was
raised for good reason: we are using sscanf() to read a "%x" format. The
documentation (man sscanf) states that this must be read into an
unsigned integer. The Sick TiM protocol documentation indeed states the
type "Uint_32" for the starting angle field, however, the range is
declared as -450000d to +2250000d.
So we need to read an unsigned int and then interpret it as a signed
integer to be compliant with sscanf and the device protocol.
Thanks to @vmatare for reporting this issue.

laser: fix type error

---

src/plugins/perception/pcl-db/ros/Makefile
src/plugins/perception/pcl-db/ros/pcl_db_roscomm_thread.cpp
src/plugins/perception/pcl-db/ros/pcl_db_roscomm_thread.h

This plugin enables access and control to pcl-db from ROS. However, so far it depended on hybris_c1_msgs for the service/message types. This, however, is no longer maintained. Move the respective types to [fawkes_msgs](https://github.com/fawkesrobotics/fawkes_msgs), which makes much more sense as a single point of entry to Fawkes-specific ROS types. The fawkes-builder images have already been updated for fawkes_msgs.

Adapt pcl-db-roscomm to fawkes_msgs

---

src/libs/aspect/inifins/blackboard.cpp
src/libs/baseapp/Makefile
src/libs/baseapp/main_thread.cpp
src/libs/baseapp/run.cpp
src/libs/plugin/manager.h

This was originally started to enable an easier migration of the [rcll-refbox](https://github.com/robocup-logistics/rcll-refbox) (or rather the disfunct [rci-refbox](https://github.com/robocup-industrial/rci-refbox)) to a newer Fawkes base system. It doesn't hurt to have these abilities in the tree so I'm proposing this for addition.

Modularize libbaseapp

---

src/plugins/asp/aspect/clingo_access.cpp
src/plugins/asp/aspect/clingo_access.h

This is a minor commit required for merging the ASP planner in fawkes-robotino. The debug level is no longer a public value, since it is an atomic value it must be treated with special care. Hence, encapsulate it in a proper API.

asp: add API to get and set debug level

---

src/tools/config/main.cpp

So far, ffconfig could only retrieve configuration values from a running Fawkes instance via network.
This PR enables to retrieve configuration values off-line from the local config files, without such a running instance. This is useful to retrieve values from a (pre-)startup script.

Enable ffconfig to read directly from file

---

.buildkite/pipeline.yml
.buildkite/steps.d/20-webview-frontend.yml

This upgrades docker Fedora build images to Fedora 29. It seems to suffice to build on Fedora 29 only, and not build on both, F28 and F29. All relevant systems are expected to be upgraded by now or shortly.
Along the image this also performs minor upgrades to the github-merged-pr and docker buildkite plugins.
Thanks to @morxa for some Fedora package fixes and rebuilds for F29 compatibility.

Upgrade build pipeline images to Fedora 29

---

src/plugins/robot-memory/robot_memory.cpp
src/plugins/robot-memory/robot_memory.h

As discovered in https://github.com/carologistics/fawkes-robotino/issues/9, check_collection_name was called in a lot of places without actually making use of the return value. The function used to check if the collection name started with a hardcoded prefix ("robmem"). Since the collection names are configurable, there is no need for enforcing robmem as a prefix for collection names. 
895c0e434 changed the behaviour of some functions, that then actually used the return value of check_collection_name, which caused some problems.
Therefore, I suggest the removal of the check completely, since it serves no real purpose.

robot-memory: remove collection name check

---

.buildkite/annotations.d/build_stats.sh

The build stats script did not account for domain repos which contain Fawkes as a sub-module.

buildkite: account for domain repos for stats generation

---

src/plugins/gazebo/gazebo.mk

Somehow the gazebo 9.6.0 pkgconfig file doesn't specify most boost
dependencies any more. This is actually just a workaround and should be
fixed upstream in the long run.

buildsys: link gazebo drivers against boost_system

---

src/libs/fvutils/cpu/mmx.h

Those modifiers are not private members but instructions to the compiler
and should not have been converted in commit c6b48abfdf0371b9d13265d8b4f9908cb175a469.

fvutils: fix underscores in __asm__ and __volatile__ modifiers

---

src/plugins/katana/goto_openrave_thread.cpp
src/plugins/katana/goto_thread.cpp
src/plugins/katana/gripper_thread.cpp
src/plugins/katana/motor_control_thread.cpp
src/plugins/katana/sensacq_thread.cpp

Fix invalid format strings in Katana that cause build failures on Fedora 30/rawhide.

katana: fix format strings

---

.clang-format

The option RawStringFormats now expects a list of delimiters for each
language.

clang-format: adapt RawStringFormats config to new file format

---

src/libs/googletest/Makefile

By being more specific in the dependencies we can avoid copying the same file twice, in turn preventing the race condition on copying which may fail in some rare cases (but especially on a loaded system such as a build host).
Fixes #62.

googletest: avoid copying files twice

---

etc/buildsys/btypes/config_sysinstall.mk

Adds ppc64le to 64-bits arch for suffix. Along the way simplify expression to be (more) readable. Found during cleanup of local branches.

buildsys: add ppc64le to list of 64-bit archs

---

.buildkite/lint

We have such a steady flow of topic branches that we did not have any instance of a build without one since the introduction of buildkite. Now, if there were indeed no topic branches, builds failed, for an example see https://buildkite.com/fawkesrobotics/fawkes-build/builds/376 (the failed linter steps).
This branches addresses this issue. I have made local tests reconstruction that situation and am confident that the issue is fixed. Only this PT without other topic branches will really tell.

Fix builds for when there are no other topic branches

---

.buildkite/lint
.buildkite/pipeline.yml

When issuing a build for an external fork repo (typically doing a rebuild on a previously rejected build) using BUILDKITE_BRANCH yields something like "user:branch" (we explicitly enabled that in buildkite
and use it for, e.g., branch name verification). This will lead the author information check to fail since it would use a commit range like "MERGE_BASE..user:branch". Fix this by using BUILDKITE_COMMIT. Make sure to add this to the environment passed to the docker containers.
Fixes the build fail in #70.

buildkite: fix builds from fork repos

---

src/plugins/mongodb/mongodb.mk

This commit fixes the build under Ubuntu 18.10. The `version.h` header in Debian's `libmongoclient-dev` package has been moved from `/usr/include/mongo` to `/usr/include/$ARCHITECTURE/mongo`.
It looks like the move happened in https://salsa.debian.org/mongodb-team/mongo-cxx-driver-legacy/commit/4d1c761a451b20c2c643380aee00ef49c34b66fb.

mongodb_log: Support Debian's mongo/version.h move

---

src/plugins/plexil/protobuf_adapter.cpp

This slipped through testing, though I cannot really tell how. Confirmed the fix with a group in KBSG's current lab course.
Fixes #71.

plexil: fix deadlock in protobuf adapter

---

.gitlint

In particular, do not allow something like "libs: somelib: message".
This should avoid further instances of the commit subject issue in #75.

gitlint: make subject regex more specific

---

src/libs/pcl_utils/pointcloud_manager.h

pretty trivial, I wonder why no compiler or any of the supposedly thorough linters warned about this...

pcl_utils: fix broken format string in exception

---

src/plugins/laser-filter/filters/projection.cpp

Fixes a faulty calculation of the angle of the ith beam for laser sensors that uses a different amount of beams than 360 or 720.

Laser Filter: Fix projection calculation for default case

---

.gitignore
etc/buildsys/root/check.mk
etc/buildsys/root/git-hooks.mk
etc/buildsys/root/root.mk
etc/git-hooks/pre-push

Our growing rule set and lack of pre-checks before pushes by committers leads to a high number of failed builds.
To improve this a little bit and train people to run "make check" before pushing soft-enforce this by installing a local pre-push hook on the first run of make. This then checks a timestamp file created/touched by "make check" to check if any of the files affected on the current branch has been modified after running the check last.
This is not bullet proof, if someone develops on the local master branch and pushes with something like "git push master:some/branch" the check would not work. However, this is then still caught by the CI builds.
We need to get better to reduce the number of builds fails and work more efficiently.

Force check before push

---

src/plugins/realsense/realsense_thread.cpp

In principle, it's a very obvious fix: If the boolean value of `rs_error_` is the guard for dereferencing it, then it **must** be set to `nullptr` after being freed. I *suppose* this fixes the realsense errors on Fedora 29, but haven't been able to test this fully. It definitely fixes a bunch of realsense-related segfaults, but I'm not yet sure whether that was the only thing preventing the realsense plugin from working on F29.

realsense: null rs_error_ field after free

---

etc/buildsys/root/git-hooks.mk

If fawkes is a submodule, the pre-hook script should be installed in
TOP_BASEDIR, not in the current directory. Also create the hooks
directory if it does not exist yet.
This fixes a build error currently occurring in carologistics/fawkes-robotino:
```
[GIT] installing pre-push hook .git/hooks/pre-push
install: failed to access '.git/hooks/pre-push': Not a directory
```

buildsys: install git pre-push hook into TOP_BASEDIR for submodules

---

src/plugins/clips-executive/clips/goals/run-one.clp

This PR fixes a bug that causes goals of sub-type `RUN-ONE-OF-SUBGOALS` to to not fail with outcome  `REJECTED` when all sub-goals are rejected.
Evaluated sub-goals of RUN-ONE-OF-SUBGOALS goals are retracted automatically after evaluation, therefore run-one goals have to be rejected if all sub-goals are `RETRACTED` with the outcome `REJECTED`.

clips-executive: fix bug in goal rejection of run-one goals.

---

src/libs/netcomm/fawkes/server_thread.cpp

A client may disconnect before we can send a message. In that case, we should just drop the message and not throw an exception.
This fixes #85.

netcomm: do not throw an exception if client is missing or not alive

---

src/libs/interfaces/NavigatorInterface.xml
src/plugins/ros/navigator_thread.cpp
src/plugins/ros/navigator_thread.h

This PR adds two new messages to the NavigatorInterface to allow sending CartesianGoto messages with a translation and an orientation tolerance.
The `ros-navigator` uses these new messages but it will stick with the tolerance set by the configuration in case any of the messages of type `CartesianGoto`, `CartesianGotoWithFrame` or `PolarGotoMessage` are sent.

ROS Navigator: allow tolerances in CartesianGotoMessages

---

src/libs/core/threading/thread.cpp

The macro names testing for glibc to guard agains non-linux pthread
implementations were wrong, so pthread names weren't set at all any
more, not even on Linux.

core: fix glibc feature tests in thread.cpp

---

src/plugins/clips/feature_blackboard.cpp

If the type of blackboard field is a boolean, the blackboard feature
treated the field as a single value field. However, this is not granted.
E.g. the RobotinoSensorInterface uses a bool array field for publishing
the states of the digital inputs.
Thus, treat bool fields similar to float or double fields and
replace false with FALSE and true with TRUE to match CLIPS boolean
representation.

clips: properly deal with bool arrays

---

cfg/conf.d/realsense.yaml
src/plugins/realsense/realsense_thread.cpp
src/plugins/realsense/realsense_thread.h

This PR makes the handling of the realsense device more robust. In particular, if the device fails intermittently and we cannot poll new frames for a while, restart the camera. In order to do this, restructure the camera initialization so we can initialize the camera in every loop if it has not been initialized. This also allows loading the plugin while the camera is not connected yet.
Note that this requires `librealsense1-1.12.3-b7a6fb9.4` ([F30 update](https://bodhi.fedoraproject.org/updates/FEDORA-2019-dfd4e95abb), [F29 update](https://bodhi.fedoraproject.org/updates/FEDORA-2019-87363450db)). Otherwise, the plugin will still segfault, because the library used to throw an exception in a separate thread.

Restart realsense if polling fails too often

---

src/plugins/clips-executive/clips/skills-actions.clp

If a skill fails, the error-msg field of the SkillerInterface is set to a string which describes the error. The plan action already had a error-msg field, but it wasnt used. On failure, set the error-msg field to the error-msg of the string

clips-executive: properly populate error-msg of plan-action

---

src/plugins/clips-executive/clips/coordination-mutex.clp
src/plugins/clips-executive/clips/wm-robmem-sync.clp
src/plugins/clips-robot-memory/clips_robot_memory_thread.cpp
src/plugins/clips-robot-memory/clips_robot_memory_thread.h

There is a potential deadlock between the clips environment and robot-memory if we do the trigger registration synchronously (#90).
To avoid the deadlock, make the register_trigger function asynchronous: It creates a future that will assert a feedback fact into the clips environment once registering the trigger has succeeded or failed. This is similar to the pattern used for `mutex_try_lock_async`.
This fixes #90.

Register robot-memory triggers asynchronously

---

src/plugins/clips-executive/clips/coordination-mutex.clp
src/plugins/clips-executive/clips/resource-locks.clp
src/plugins/robot-memory/robot_memory.cpp

This PR fixes 3 minor issues in locking and lock expiring:
- Due to the introduction of lock expiring, a mutex can have multiple requests pending. At some places, a mutex was checked if an unlock is pending, without taking this into account. 
- Occasionally it can happen, that multiple robmem-trigger of the same mutex gets asserted. Clips used to deal with them, starting with the newest. If the trigger indicates an unlock, followed by a lock, clips would have applied them the wrong way around, resulting in a wrongfully unlocked mutex. This is fixed by enforcing clips to handle the oldest robmem-trigger first
- The update document in the expire locks function was created wrongly.

Clips-Executive lock fixes

---

src/plugins/clips-executive/clips/coordination-mutex.clp

On lock renewal, the response of the mutex would be changed from
pending to acquired or rejected upon the receival of the mutex-op-feedback
fact. The decision when the next lock renewal have to be started is
based on the lock-time of the mutex. This would have been updated only
if the robmem-trigger of the renewal arrived before the mutex-op-feedback.
If this was not the case, the renewal started again instantly
In order to prohibit this race, we have to adapt the response field
directly when receiving the robmem-trigger, instead of a seperate rule. To make
this consistent with normal locking, this is changed generally for all requests

clips-executive: change lock response field directly

---

src/plugins/clips-executive/clips/coordination-mutex.clp
src/plugins/clips-executive/clips/resource-locks.clp

We wanted to check if UNLOCK is in the pending requests field. The logic was inverted in the last Pull Request, leading to resource locks never actually be requested to unlock.

clips-executive: fix member check for pending requests

---

src/plugins/clips-executive/clips/wm-robmem-sync.clp
src/plugins/clips-robot-memory/clips_robot_memory_thread.cpp
src/plugins/clips-robot-memory/clips_robot_memory_thread.h
src/plugins/robot-memory/robot_memory.cpp
src/plugins/robot-memory/robot_memory.h

Sometimes we want to check a robot-memory collection and assert all worldmodel-facts that are currently missing. This is done by creating a regex query for all wm-fact keys that are configured to be synced. This PR fixes the regex query creation and adapts the query execution to the changes of the new mongocxx-driver.

Cx restore prefixes: Fix query creation and execution

---

src/plugins/realsense/realsense_thread.cpp
src/plugins/realsense/realsense_thread.h

The Realsense gets drowned by pol querries. Delaying the pol after an error occurs, increases chance to regain controll of the device

delay next poll if error while polling for realsense data occurs

---

src/libs/config/yaml.cpp

In several occasions it would be useful to push host specific host.yaml files.
Until now, this was not possible as the host specific config file was named equally for all hosts.
This PR introduces changes to load config styles named `*<>*.yaml`, where `<>` is replaced by the hostname. See also PR [#164](https://github.com/carologistics/fawkes-robotino/pull/164) of the fawkes-robotino repo.

Allow pushable host specific config files.

---

src/libs/interface/message.h
src/libs/interfaces/generator/cpp_generator.cpp
src/libs/interfaces/generator/parser.cpp

During syncing of fawkes interface messages from different fawkes instances via the BlackboardNetHandler the message type is truncated to `INTERFACE_MESSAGE_TYPE - 1` characters. However, when the serialized message arrives at the other fawkes node, a new blackboard interface message is generated. To trigger the creation of the correct message type, the truncated message type is compared with possible message types of the specific interface. This comparison is done over `INTERFACE_MESSAGE_TYPE` characters and thus include a null terminator, leading to a not recognized message type, whenever the original interface message type includes more than `INTERFACE_MESSAGE_TYPE - 1` characters. This PR corrects the number of characters which are compared to `INTERFACE_MESSAGE_TYPE - 1` characters. …

Check for collisions in truncated interface message type

---

src/libs/interface/message.cpp
src/libs/interfaces/generator/cpp_generator.cpp

When copy-constructing an interface message, copy the sender id and the thread name from the copied message instead of reinitializing them with 0 and the current thread's name respectively.
Also adapt the interface generator to actually use the copy constructor of `Message` when copy-constructing a message of a particular interface.
I encountered this bug while working on a skiller simulator, which would provide the same interface as the Skiller but without actually executing any skills. There, the skillgui would not get exclusive control because the message is copied and the copied message wouldn't contain the correct sender ID. This does not occur with the real skiller, because there, the message processing happens in lua and therefore, the message is never copied.

Keep sender info when copying an interface message

---

etc/buildsys/btypes/rules_sysinstall.mk
src/plugins/flite/Makefile
src/plugins/flite/synth_thread.cpp
src/plugins/mongodb/Makefile
src/plugins/pddl-planner/Makefile
src/plugins/pddl-robot-memory/Makefile
src/plugins/perception/pcl-db/Makefile
src/plugins/webview/Makefile
src/plugins/webview/frontend/Makefile

Adapt the sysinstall target to recent changes in the build system.
This is a step towards fixing the FTBFS status in Fedora.

Fix make target 'install'

---

src/libs/fvutils/color/colorspaces.cpp
src/libs/fvutils/color/colorspaces.h
src/libs/fvutils/color/conversions.cpp
src/libs/fvutils/color/rgb.cpp
src/libs/fvutils/color/rgb.h

This colorspace is useful, as it is widely used as input data format for tensorflow graphs.
By introducing the conversion methods directly into the firevision library, the use of specialized conversion methods in each plugin itself is reduced, leading to more flexible code.

Add (RGB/BGR)_Float as colorspaces

---

src/libs/fvcams/Makefile

Before only a warning for libjpeg is displayed. This PR introduces an analog warning for libpng.

Add warning regarding png support while building fvcam

---

src/plugins/refboxcomm/Makefile
src/plugins/skiller-simulator/Makefile
src/plugins/skiller-simulator/exec_thread.cpp
src/plugins/skiller-simulator/exec_thread.h
src/plugins/skiller-simulator/skiller_simulator_plugin.cpp
src/plugins/skiller-simulator/skiller_simulator_plugin.h

This provides a new plugin `skiller-simulator` that provides the same interface as the real skiller but never really executes a skill. Currently, the implementation is rather simple and is more a mockup than a simulation, each skill just takes a fixed amount of time to execute. However, this is already sufficient for many purposes related to agent development.
In the future, this could possibly be extended by having per-skill execution times or even by reading old log files to get a realistic execution time.
This implements #114.

Add plugin to simulate skill execution

---

src/libs/core/utils/lock_hashmap.h
src/libs/core/utils/lock_hashset.h
src/libs/fvutils/color/yuv.cpp
src/libs/netcomm/utils/ntoh64.h
src/plugins/clips/feature_blackboard.cpp
src/plugins/openrave/environment.cpp

Some compiler macros (and other variables and names) were changed erroneously when adapting the underscores in private member variable names. Change them back to the correct names.
Candidates for renaming were found with `git grep '___'`.
This fixes #93.

Fix underscores in compiler macros

---

src/plugins/clips-executive/clips/wm-robmem-sync.clp
src/plugins/clips-robot-memory/clips_robot_memory_thread.cpp

We may sometimes get a different mongocxx exception, e.g., a `query_exception`, when querying the database. Catch all those exceptions by catching the super-type `mongocxx::exception`.
Also print an error in the clips-executive if we lose an update by a mongocxx exception.

Catch all mongocxx exceptions in clips-robot-memory

---

src/plugins/robot-memory/Makefile
src/plugins/robot-memory/computables/computables_manager.cpp
src/plugins/robot-memory/computables/computables_manager.h
src/plugins/robot-memory/event_trigger_manager.cpp
src/plugins/robot-memory/event_trigger_manager.h
src/plugins/robot-memory/robot_memory.cpp
src/plugins/robot-memory/robot_memory.h
src/plugins/robot-memory/robot_memory_thread.cpp
src/plugins/robot-memory/robot_memory_thread.h

Decouple the thread from the main loop and let it run continuously.
Robot memory takes a long time to process trigger events, which blocks
the main loop and results in a lot of loop time warnings.
By default, use the main loop time as desired loop time and wait at the
end of the loop if the loop completed faster than desired. The loop time
can be overwritten in the config.
The disadvantage of running it continuously is that the triggers do not
run in the SENSOR_PROCESS hook anymore but may be triggered at any time.
However, as the thread takes too long and therefore is decoupled from
the main loop anyway, this is already happening now. Thus, this should
do no harm.
Also add some time tracking to robot memory, which can be enabled by setting the respective CFLAG.
Running the thread in …

robot memory: run thread in continuous mode

---

src/plugins/mongodb/mongodb_instance_config.cpp
src/plugins/mongodb/mongodb_instance_config.h

Since mongodb 2.6.0, the bind ip no longer defaults to 0.0.0.0 (all
interfaces), but to 127.0.0.1 (the local interface only). Allow setting
the bind ip in the config and default to 0.0.0.0 again.

mongodb: make mongod's bind_ip configurable

---

etc/buildsys/format.mk
etc/buildsys/root/check.mk
etc/buildsys/root/format.mk
etc/format-scripts/check-all-files.sh
etc/format-scripts/check-branch-files.sh

If we call `git ls-files *.{h,cpp}`, then (depending on the shell), the
expansion of `*` may already be done by the shell instead of git. This
is undesired, as the shell does not list files in sub-directories, in
contrast to git. Thus, to make sure that we list all files, escape the
glob `*` so we always pass it to git. This issue occurs when using zsh,
but probably may also occur with bash, depending on the shell
configuration.
To test:
```
$ cd src/plugins/robot-memory/
$ vim computables/computables_manager.cpp
[ change the formatting ]
$ make format
```
Without this change, the file `computables/computables_manager.cpp` would not be re-formatted (at least when using zsh as shell).

buildsys: expand globs in git ls-files with git, not the shell

---

src/plugins/clips-executive/clips/wm-robmem-sync.clp

The function simply removes all documents from the synced robot memory
collection.

clips-executive: add function wm-robmem-flush

---

src/libs/interface/message.cpp

This should fix the message destructor coredumps, thus resolve #124.
For trying: Use the description in the issue comment and spam the plugin with at least 60 messages.
No coredumps were notable anymore after applying this patch.

Properly initialize fieldinfo_list_

---

etc/buildsys/lua_check.mk

Gentoo systems now also follow the established lib32/lib64 multilib
layout.

buildsys: update tolua_check

---

src/plugins/robotino/direct_com_message.cpp

This PR fixes a bug in the direction communication with the robotino firmware.
The bug appeared **only** if the message sent to the robotino firmware needed to be escaped. In this case, however, the robotino firmware consequently ignored the incoming message.
This bug was definitely the reason for issue #129 and could be also reason for other sporadic events, in which the robotino did not want to start driving.
A more specific explanation of the issue is given in #129.
This fixes #129.

Consider all bytes during escape

---

src/plugins/clips-executive/clips/lock-actions.clp
src/plugins/clips-executive/clips/resource-locks.clp

This PR fixes issues when unlocking an already open lock.  There will not be an unlock response,
because no unlock took place. Currently this causes behaviour such as goals getting stuck on freeing resource locks, if a lock was somehow lost. To recover from failures like this, we can simply ignore the response while unlocking,if the lock is open.

clips-executive: ignore response when unlocking a mutex

---

cfg/conf.d/realsense2.yaml
src/plugins/Makefile
src/plugins/realsense2/Makefile
src/plugins/realsense2/realsense2_plugin.cpp
src/plugins/realsense2/realsense2_thread.cpp
src/plugins/realsense2/realsense2_thread.h

Adds Plugin for the librealsese2 compatible Depth Cameras
See -> #110
Requires at least librealsense2  version 2.16 if used  on kernel >= 4.16 to be build
use this to install compatible version. 
dnf --enablerepo=updates-testing-modular module install librealsense/dev

add new realsense2 plugin 

---

src/plugins/robot-memory/robot_memory.cpp

This PR just removes a few compiler warning and fixes some legitimate build errors that came up on my machine, presumably due to GCC 9.1.0.

Fix compiler warnings in robot memory

---

src/lua/fawkes/fsm.lua

A state's reset() method is a user-supplied method that is supposed to
perform custom cleanup actions on skill reset (e.g. when skill is
cancelled to execute another one). When implementing this method, a user
expects that the last state of the skill still exists, in particular
that the fsm.vars table hasn't been cleared, yet.

skiller: call states' reset() before clearing vars

---

src/lua/fawkes/tfutils.lua

add a missing error message in the case of an unavailable transform, and
log all errors at the proper loglevel.

skiller: improve tfutils error messages

---

src/plugins/Makefile

Build it after the skiller because we use the skiller's interfaces.

plugins: build skiller-simulator

---

src/plugins/clips-executive/clips/wm-robmem-sync.clp

If we get a trigger for the deletion of a wm-fact, also retract the sync
map entry in addition to the wm-fact. Otherwise, we cannot distinguish
whether we deleted the fact locally or received a delete trigger for the
fact, and therefore trigger another deletion. This may cause issues
especially if the trigger is delayed, because we may delete facts on
other robots that have been created after the original deletion.

clips-executive: retract sync-map if we receive a delete trigger

---

src/plugins/clips-executive/clips/wm-robmem-sync.clp

If we receive an update for a known fact with a newer timestamp than our
own, also update the local timestamp. This ensures that we keep the fact
if another agent deleted and re-adds the fact, even if the triggers for
those events reach us in the wrong order.

clips-executive: update timestamp when updating known fact

---

src/plugins/clips-executive/clips/resource-locks.clp

Adapt the resource locking so it properly works even if multiple (local) goals require the same resources.
With this PR, we now immediately reject a goal if we have already acquired a required resource for another goal. Previously, we would wait until the other goal is finished and then try continue acquiring the resource.
We now explicitly track for which goal we requested a resource with the `resource-locks-resource-requested-for` fact.

CX: resource locking with multiple goals

---

etc/buildsys/root/check.mk
etc/buildsys/root/git-hooks.mk
etc/git-hooks/pre-push

Remove the quickdoc from the enforced checks in the pre-push hook. The quickdoc check takes a long time and quickly gets annoying, without only little added benefit, as we do not change the API that often.
Note that the full check is still run in buildkite, so missing documentation will trigger a failed build.

Remove doc check from enforced check in pre-push hook

---

src/plugins/realsense/realsense_thread.cpp
src/plugins/realsense/realsense_thread.h

if an error occurs the old realsense is drowned in querry requests. delaying these requests
reduces overhead on the realsense side and hopefully increases stability

realsense add delay between pols if error occur

---

etc/buildsys/root/check.mk
etc/buildsys/root/docs.mk

Whenever a `*.cpp` or `*.h` file exists in the git basedir, the license and doxygen check doesn't work as expected, since the bash already expands `*.{cpp,h}`.

Escape * to obtain git files

---

src/plugins/clips-executive/clips/coordination-mutex.clp
src/plugins/clips-executive/clips/goal.clp
src/plugins/clips-executive/clips/resource-locks.clp

Add a slot `verbosity` with the allowed values `DEFAULT` and `QUIET` to the goal template and remove log messages for those goals for any typical behavior.
Also redirect log messages about lock renewal to the debug output.

Make log verbosity tunable for each goal

---

src/plugins/robot-memory/robot_memory.cpp

If we did not update any document (and find_one_and_update returned an
optional that does not contain a value), then we failed to renew the
lock. Thus, we should return true if and only if a document was
returned.
The rest of the code is already prepared to process the return value, this is the missing bit to handle renewal failures correctly.

robot-memory: renew_lock should only return true on success

---

src/plugins/clips-executive/clips/coordination-mutex.clp

We receive the result of a mutex operation (e.g., lock) by a trigger
event. If the trigger is not yet registered, we do not get the
information. Thus, we need to wait for the trigger before we do any
calls to robot-memory.
Co-Authored-By: Daniel Habering <daniel.habering@rwth-aachen.de>

clips-executive: only send mutex queries if the trigger is registered

---

src/plugins/clips-executive/clips/goal.clp

Changes the type of the goal priority to float. There is no practical reason to enforce priorities to be of type INTEGER. However, with a float typed priority we can use small differences in priorities to determine two, equally typed goals eg by distance they have to travel by adding a value between 0 and 1 to the base priority of the class.

cx: change goal priority type to float

---

etc/git-hooks/pre-push

Before, the `pre-push` hook only emits a warning, that `make check` should be run.
This PR changes this behaviour; `make check` is automatically run if necessary.

Run make check if needed

---

src/plugins/clips-robot-memory/clips_robot_memory_thread.cpp

A bsoncxx:exception is no sub-type of mongocxx::exception, thus we need
to catch it separately. If both exceptions are possible, catch a
std::system_error, which is a super-type of both.

clips-robot-memory: catch bsoncxx::exceptions

---

cfg/conf.d/realsense.yaml
src/plugins/realsense/realsense_thread.cpp
src/plugins/realsense/realsense_thread.h

config param and variable "delay_between_poll_errors" had a typo.

realsense: fix typo in delay config value name

---

src/plugins/ros/navigator_thread.cpp

In case the move_base ROS node is not running notify by setting a proper
error code on the interface.

Set error code in NavigatorInterface from ros_navigator if move_base is unavailable

---

src/plugins/laser-filter/filter_thread.cpp
src/plugins/laser-filter/filters/map_filter.cpp
src/plugins/laser-filter/filters/map_filter.h

The number of pixels to be filtered by the map_filter were hard-coded
previously. Now configuration can be used to set the value. A default
value of 2 pixels is used in case the configuration won't set a certain
value.

Allow configuration of the laser-filter map_filter's pixels

---

src/plugins/clips-robot-memory/clips_robot_memory_thread.cpp
src/plugins/robot-memory/event_trigger_manager.cpp

MongoDB 4 no longer allows registering a change stream with a `maxAwaitTimeMS` of 0ms. Set it to a very low value of 10ms, such that it almost immediately returns.

Set change stream wait time to 10ms for MongoDB 4

---

src/plugins/clips-executive/clips/wm-robmem-sync.clp

If we delete a fact, we should not also delete the sync map entry, because then we lose the information when the fact was deleted. This becomes important if we later get an update trigger, as we need to know if the update was before or after the deletion.
For the same reason, also create a new sync map entry if we get a delete trigger but we have never seen the fact before.

clips executive: keep sync map entry on delete

---

src/plugins/clips-executive/clips/coordination-mutex.clp

Abort a pending lock renewal if:
* the lock's state is `OPEN`, disregarding the state of the request
* the lock is owned by another identity

Let lock renewal fail if the lock has expired or is owned by another identity

---

src/plugins/skiller-simulator/exec_thread.h

Fix the include guard so it actually guards all declarations/definitions.
Found by LGTM!

skiller-simulator: fix misplaced include header guards

---

src/plugins/robot-memory/robot_memory.cpp

The find_one_and_update query may fail and return an optional without a
value. Check whether a document returned and also check whether it
contains the expected value.

robot-memory: return true in renew and unlock only if query succeeded

---

src/libs/interfaces/generator/cpp_generator.cpp

Packing interface structs is a bad idea if we access the pointer of a
member of that struct, as the pointer may now be unaligned. We have
never observed memory issues with blackboard interfaces, so packing
seems to be unnecessary anyway.
This effectively reverts 46f1e250c8f6b5938a05a1ad4a347f13285519cb,
except that it removes every packing.
This fixes an address-of-packed member warning that has been added in
GCC9.

Do not pack interface structs

---

src/libs/pcl_utils/utils.h

ROS melodic also ships with an updated PCL. Change the order of the
version checks so we first check the PCL version, and only then check if
we have an old PCL with ROS.

Adapt pcl_utils to ROS melodic with updated PCL

---

.lgtm.yml

This package previously had to be installed through a strange hack, but  that hasn't been necessary in a long time. The hack will stop working when the LGTM build environment is upgraded to Ubuntu 19.10.
I've tested that this works on https://lgtm.com/logs/ad4d8523ce6b13ee95871eeb36feb3364f2139f4/lang:cpp

lgtm: install libpcl-dev directly

---

src/libs/utils/math/lines.h

There is no need to pass the line ends by value, pass them by const
reference instead.

utils: pass by const ref instead of by value in line segmentation

---

src/libs/interface/interface.cpp
src/libs/interface/message.h
src/libs/interfaces/generator/cpp_generator.cpp

So here's a crazy late-night idea: What if blackboard interfaces only reported change when the data *actually changed*, and not whenever any setter has been called? Turns out it's relatively easy to implement, and in my tests so far it's looking good. But obviously this affects everything and will need to be tested in the real world as well. Just putting this out there ;-)

interfaces: notify of change only if true

---

etc/format-scripts/check-file.sh

A non-existing file cannot be in the wrong format, so the
`check-file.sh` script should not fail, but exit with success.
This fixes an issue where the check-format build target passes a deleted
file to the script. Rather than filtering out those files in the caller,
also accept non-existing files and immediately succeed.
This fixes #182.

format-scripts: do not fail if file does not exist

---

src/lua/skiller/subskill_jumpstate.lua

In order to be able to evaluate the state of the substring in the
exit function of the skilljumpstate, e.g. checking the error field,
we have to call the exit function before resetting the subskill.

skiller/subskill_jumpstate: call exit before resetting the subskill

---

src/libs/Makefile
src/libs/interfaces/ProtobufPeerInterface.xml
src/libs/protoboard/Makefile
src/libs/protoboard/blackboard_manager.cpp
src/libs/protoboard/blackboard_manager.h
src/libs/protoboard/plugin.h
src/libs/protoboard/protoboard_types.h
src/libs/protoboard/protobuf_thread.cpp
src/libs/protoboard/protobuf_thread.h
src/libs/protoboard/protobuf_to_bb.cpp
src/libs/protoboard/protobuf_to_bb.h

This should be close to merge ready. It could benefit from an internal redesign to simplify the call structure within the template code, but the external interface is fine. Only thing that's missing is an explicit documentation of the external interface, but we do have the [`protobuf-rcll` plugin](https://github.com/carologistics/fawkes-robotino/pull/328) as an example in fawkes-robotino.

protoboard: Template-based, typesafe conversion between ProtoBuf and the blackboard

---

cfg/conf.d/gologpp.yaml
src/plugins/gologpp/Makefile
src/plugins/gologpp/gologpp_fawkes_backend.cpp
src/plugins/gologpp/remote_skiller_executor.cpp
src/plugins/gologpp/remote_skiller_executor.h
src/plugins/gologpp/skiller_action_executor.cpp
src/plugins/gologpp/skiller_action_executor.h
src/plugins/gologpp/test-scenarios/blocksworld-multi-agent/blocksworld-multi-agent.gpp
src/plugins/gologpp/test-scenarios/blocksworld-multi-agent/logger.gpp

Provide a simple way to use Golog++ in a multi-agent setting with a central reasoner by allowing remote skill execution. In particular, add a `RemoteSkillerActionExecutor` that executes a skill on a remote fawkes instance by connecting to the remote blackboard.
Each `RemoteSkillerActionExecutor` instance is created with an agent name and it only executes a given activity if the activity's agent parameter (`robot` by default) matches the name of the remote agent. The remote agents are defined in the config.
If none of the remote agents can execute the activity, the local `SkillerActionExecutor` will be tried.
Also extend the blocksworld test scenario to a multi-agent system. To run it, do the following:
1. Change the spec in the config to `blocksworld-multi-agent`
2. Start a first fawkes …

Golog++ remote execution for a central multi-agent approach

---

.github/stale.yml

This gives more time to work on an issue and seems more realistic with
our usual workflow.

github: wait for 90 days before marking an issue as stale

---

src/plugins/clips-robot-memory/clips_robot_memory_thread.cpp
src/plugins/clips-robot-memory/clips_robot_memory_thread.h
src/plugins/robot-memory/robot_memory.cpp
src/plugins/robot-memory/robot_memory.h

This PR reworks the way robot-memory utilizes mongocxx to dump monogdb collections to a file and restore them. Additionally, it adds the clips bindings for the dumping and restoring functionality.
Help needed: For dumping, the ip and the port of the database has to be passed. I am struggeling to find a way to determine the ip  and the port of the corresponding database of the collection that should be dumped on the fly.

Rework robotmemory collection dump and restore

---

etc/buildsys/gui.mk

As per title - fix for https://github.com/fawkesrobotics/fawkes/issues/195.

Suppress deprecation warnings for unpatched packages depending on GLib >= 2.62.

---

src/plugins/gologpp/exog_manager.cpp

Minor compatibility fix for the most recent `golog++` version which factors the `Grounding<T>` template into a separate header

gologpp: include facored-out header file

---

src/plugins/robot-memory/Makefile
src/plugins/robot-memory/robot_memory.cpp
src/plugins/robot-memory/robot_memory.h

This PR contains some minor improvements as follow-up to #192:
* Always use `split_db_collection_string` instead of parsing the db/collection string manually (fix #202)
* Get rid of "noop" as a special collection name for using the input collection as target collection. Use the empty string instead (which is always an invalid collection name) (fix #201)
* Do not hardcode host/port in dump and restore (fix #199)

Robot memory dump/restore improvements

---

cfg/conf.d/skiller-simulator.yaml
src/plugins/Makefile
src/plugins/skiller-simulator-navgraph/Makefile
src/plugins/skiller-simulator-navgraph/navgraph_estimator.cpp
src/plugins/skiller-simulator-navgraph/navgraph_estimator.h
src/plugins/skiller-simulator-navgraph/skiller_simulator_navgraph_plugin.cpp
src/plugins/skiller-simulator-navgraph/skiller_simulator_navgraph_thread.cpp
src/plugins/skiller-simulator-navgraph/skiller_simulator_navgraph_thread.h
src/plugins/skiller-simulator/Makefile
src/plugins/skiller-simulator/estimators/config_estimator.cpp
src/plugins/skiller-simulator/estimators/config_estimator.h
src/plugins/skiller-simulator/exec_thread.cpp
src/plugins/skiller-simulator/exec_thread.h
src/plugins/skiller-simulator/execution_time_estimator.cpp
src/plugins/skiller-simulator/execution_time_estimator.h
src/plugins/skiller-simulator/execution_time_estimator_aspect/execution_time_estimator_aspect.cpp
src/plugins/skiller-simulator/execution_time_estimator_aspect/execution_time_estimator_aspect.h
src/plugins/skiller-simulator/execution_time_estimator_aspect/execution_time_estimator_aspect_inifin.cpp
src/plugins/skiller-simulator/execution_time_estimator_aspect/execution_time_estimator_aspect_inifin.h
src/plugins/skiller-simulator/tests/Makefile
src/plugins/skiller-simulator/tests/test_skill_parser.cpp

Enhance the skiller simulator with estimated skill execution times. The skills will no longer always execute exactly for 1 second, but instead compute an estimate and run the skill for that estimated time.
To estimate the execution time of a skill, the skiller simulator has a set of estimators:
* Each estimator has a function `can_execute` that returns true if the estimator can give an estimate for the given skill
* It also has a function `get_execution_time` that actually computes the estimated execution time
* Third, it has a function `execute` that is called when the skill has finished executing. This is used to apply possible side effects (e..g, after a `goto`, save the new position)
An estimator can be added by adding the `ExecutionTimeEstimatorsAspect` and calling `register_provder` …

Add skill execution time estimates to the skiller simulator

---

src/plugins/navgraph/visualization_thread.cpp
src/plugins/navgraph/visualization_thread.h

Split navgraph visualization markers into groups and republish the marker in every iteration. This allows filtering the markers by selecting/unselecting namespaces in rviz. It also fixes an issue that the navgraph nodes cannot be displayed if rviz does not get the initial visualization marker message.

Split navgraph visualization markers into groups

---

etc/buildsys/catch2.mk
etc/buildsys/rules.mk
src/libs/core/tests/Makefile
src/libs/core/tests/test_circular_buffer.cpp
src/libs/kdl_parser/tests/Makefile
src/libs/syncpoint/tests/Makefile
src/tools/Makefile
src/tools/gtest/Makefile
src/tools/gtest/gtest_fawkes.cpp

Integrate catch2 into our build system. Also make some restructuring to the test case management: Previously, we assumed all test binaries to have a name `gtest_$testname`. This assumption was implicit and easy to miss. Instead, have separate test sets `BINS_gtest` and `BINS_catch2test` for the test binaries of the respective testing framework.
Adapt all tests to the changes. Also switch the circular buffer tests to catch2, mainly to test how catch2 works.
Note that catch2 produces slightly funny-colored output with our build system. This should be fixed with catchorg/Catch2#1864.

Add support for the testing framework catch2

---

src/plugins/skiller-simulator/tests/Makefile

The recent changes from #204 and #197 were incompatible, resulting in the tests from the skiller simulator (#197) not being built. This PR fixes the tests.

skiller-simulator: adapt tests to changes in the build system

---

.buildkite/pipeline.yml

Update buildkite to use Fedora 31 instead of Fedora 30.
The main work (the container images) for this was done in https://github.com/fawkesrobotics/docker-robotics.

Switch to Fedora 31 for buildkite builds

---

src/plugins/clips-executive/clips/wm-robmem-sync.clp

This PR ensures that wm-sync triggers from robot memory are processed in the same order that they are received. This aligns with the behaviour for coordination mutexes: https://github.com/fawkesrobotics/fawkes/blob/6a006f7b19f468b35e6e01c74b55bfcb6c2e6c0d/src/plugins/clips-executive/clips/coordination-mutex.clp#L478-L482

clips executive: process wm-sync triggers from old to new

---

.buildkite/pipeline.yml
.buildkite/test
etc/buildsys/root/root.mk
etc/buildsys/root/test.mk
src/libs/netcomm/dns-sd/avahi_thread.cpp
src/libs/netcomm/dns-sd/avahi_thread.h
src/plugins/clips/aspect/Makefile
src/plugins/clips/aspect/clips_env_manager.cpp
src/plugins/clips/aspect/clips_env_manager.h
src/plugins/gazebo/gazsim-comm/Makefile

Provide the capability of running integration tests. In particular:
* Add a build target `integration-test`. The target expects tests to be located in `$(TOP_BASEDIR)/tests.d` and it executes all tests sequentially.
* Prepare buildkite to run integration tests and also upload the results as artifacts.
* Fix #213, which causes high CPU loads in containers
* Provide a CLIPS function `quit` to quit Fawkes from within CLIPS. This allows to have a test controller in CLIPS that quits as soon as all tests have run.
* Do not link `gazsim-comm` against `fawkesgazeboaspect`. This is only a workaround for a linking issue in containers. For some reason, gazebo is not linked correctly in containers, resulting in runtime crashes caused by the dynamic linker which cannot find `libQt5Core`. This is in …

Add a build target for integration tests

---

.buildkite/lint

The variable `EMAILS` is an array and may contain more than one value.
Properly expand the array before iterating over it.

buildkite: fix loop over emails in build creator check

---

src/plugins/gazebo/gazsim-robotino/gazsim_robotino_thread.cpp
src/plugins/gazebo/gazsim-robotino/gazsim_robotino_thread.h

Writing to RobotinoInterface to gazsim-robotino plugin (moved from fawkes-robotino)
- Adapting to the new gripper hardwar, the puck sensor is now connected to the robotino input  -- white cable on    DI1 and black on DI2

gazebo-robotino: react on gripper has puck msg

---

cfg/conf.d/hardware-models.yaml
cfg/config.yaml
cfg/hardware-models/gripper.yaml
cfg/hardware-models/move-base.yaml
src/plugins/Makefile
src/plugins/hardware-models/Makefile
src/plugins/hardware-models/hardware_models.clp
src/plugins/hardware-models/hardware_models_plugin.cpp
src/plugins/hardware-models/hardware_models_thread.cpp
src/plugins/hardware-models/hardware_models_thread.h
src/plugins/hardware-models/interfaces/HardwareModelsInterface.xml
src/plugins/hardware-models/interfaces/Makefile

This PR adds a plugin which parses Config files defining models for hardware components given as finite state machines. These finite state machines are added to a clips environment.
Additionally, this plugin offers an interface, which can be used for informing about state changes

Add hardware model parsing

---

etc/buildsys/config.mk

ldoc is a replacement for luadoc to generate documentation for lua.
luadoc does not work with lua 5.3 and is broken on recent Fedora
releases.
This fixes #220.

buildsys: use ldoc instead of luadoc

---

src/libs/pcl_utils/comparisons.h
src/libs/pcl_utils/compatibility.h
src/libs/pcl_utils/utils.h
src/libs/protoboard/protobuf_thread.cpp
src/libs/protobuf_clips/communicator.cpp
src/libs/protobuf_comm/peer.cpp
src/libs/utils/sub_process/proc.cpp
src/plugins/gazebo/gazsim-comm/gazsim_comm_thread.cpp
src/plugins/imu/imu_cruizcore_xg1010.cpp
src/plugins/perception/pcl-db/pcl_db_merge_pipeline.h
src/plugins/robot-memory/computables/computables_manager.h
src/plugins/robot-memory/event_trigger_manager.h
src/tools/laser_calibration/laser_calibration.cpp

main thing is that with boost 1.73, the `boost::bind` placeholders `_1`, `_2` etc. aren't declared in the global namespace any more. One has to be `using namespace boost::placeholders` to make them available. PCL 1.11 fixes some related issues (1.9 doesn't compile against boost 1.73), but also brings some other API changes, mainly eliminating `boost::shared_ptr` completely from the PCL API. They've had a `pcl::shared_ptr` typedef for a while, so using that should maximize compatibility.

fixes for boost 1.73 and PCL 1.11

---

src/lua/skiller/subskill_jumpstate.lua

Currently if you misspell the skillname in `init()` when setting `self.args[skillname]` the skill will be called, but without any arguments.
If you misspell the skillname you add another entry to the `self.args` dictionary, thus changing its size.
This PR adds a hint for those cases, aiming to improve debugging, since before it would warn you about calling the skill without any arguments
1. Checking for spelling mistakes could be done with costly regexes
2. And might result in many false positives if similar skillnames are used
This supersedes #216.

Comparing the keys of self.args before and after calling self:init()

---

src/libs/protobuf_comm/Makefile
src/plugins/gossip/aspect/Makefile
src/plugins/gossip/gossip/Makefile

I've been merging this locally since around boost-1.70, but apparently no one else is seeing the issue?
So the issue is that on these libs/plugins, `-lpthread` was implicitly added before (through `boost::asio` I suspect), which it is not any more. So although no one else is experiencing this problem currently, it doesn't hurt to put it in and it should increase portability.

explicitly link pthread with boost::asio

---

src/libs/config/config.tolua

These changes are needed for this PR: https://github.com/carologistics/fawkes-robotino/pull/382
It adds the functions `get_float_or_default` and `get_int_or_default` to the tolua interface

config: Add get_float/int_or_default to tolua

---

etc/buildsys/fvconf.mk

The buildsys was assuming that the opencv libs can be found in the
standard library search paths. Now that opencv-3 is in the process of
being phased out of distros, that may not be true any more, so we need
to query pkgconfig for the correct library search paths as well.

buildsys: use opencv supplied library dir

---

src/libs/webview/microhttpd_compat.h
src/libs/webview/request.cpp
src/libs/webview/request_dispatcher.cpp
src/libs/webview/request_dispatcher.h
src/libs/webview/server.cpp
src/plugins/Makefile

This is adapted from robocup-logistics/rcll-refbox#83 (done by @TarikViehmann).
Needed to fix [recent build failures on an updated Fedora 32](https://buildkite.com/fawkesrobotics/fawkes-build/builds/1317#cdfe9924-39ca-4d0b-b0d4-76e67877e6a2).

Adapt webview to updated libmicrohttpd

---

etc/buildsys/lua.mk

As per subject - without this change the `%_tolua.cpp` target in `lua.mk` results in an endless loop because [this part](https://github.com/fawkesrobotics/fawkes/blob/2d4b44e3b9818e29f836fde02c2a503fc5485865/etc/buildsys/lua.mk#L34) pipes the output after the appropriate filtering. However as the prerequisites are empty, there is nothing to pipe.

Adapt Lua macros to changes introduced in GNU Make 4.3

---

etc/buildsys/ros.mk
src/libs/logging/fd_redirect.cpp
src/libs/webview/webview.mk
src/plugins/gazebo/gazebo.mk
src/plugins/gazebo/gazsim-localization/gazebo-plugin/gps.h
src/plugins/gazebo/gazsim-robotino/gazebo-plugin-gyro/gyro.h
src/plugins/gazebo/gazsim-robotino/gazebo-plugin-motor/motor.h
src/plugins/laser/sick_tim55x_ethernet_aqt.cpp
src/plugins/nao/button_thread.cpp
src/plugins/nao/dcm_thread.cpp
src/plugins/openprs/openprs_thread.cpp
src/plugins/openprs/utils/openprs_mp_proxy.cpp
src/plugins/openprs/utils/openprs_server_proxy.cpp
src/plugins/openrave/environment.cpp
src/plugins/plexil/protobuf_adapter.cpp
src/plugins/robot-memory/event_trigger_manager.cpp
src/plugins/robotino/direct_com_thread.cpp

boost 1.73 deprecates global placeholders. Adapt by
* avoiding the use of global placeholders (use `boost/bind/bind.hpp` instead of `boost/bind.hpp`)
* using the placeholders namespace where necessary
* disabling the deprecation warning where we include external headers which trigger the warning

Adapt to boost 1.73 (Fedora 33)

---

src/plugins/webview/Makefile

This is a follow-up to #247: the webview plugin did not use the webview build flags, therefore still generating warnings.

webview: use libmicrohttpd build flags

---

src/plugins/clips-robot-memory/clips_robot_memory_thread.cpp
src/plugins/clips-robot-memory/clips_robot_memory_thread.h

The way mongocxx-3 handles arrays has changed, which is why this was
removed when migrating to the new driver. But there is still a way to
create an array, we just need to adapt the function signature.
This is ported from https://github.com/robocup-logistics/rcll-refbox/commit/ba88b1459158d58e62f2182a37d0173008932f7e.

clips-robot-memory: implement bson array creation functions

---

src/plugins/clips-executive/clips/coordination-mutex.clp
src/plugins/clips-executive/clips/lock-actions.clp
src/plugins/clips-executive/clips/wm-robmem-sync.clp

We should never call mutex-try-lock-async if the mutex is already
locked. Similarly, if there is already a pending request, we should not
send another request. Instead, let the action directly fail.
Also add a safe guard: If we receive an update that we have locked a mutex, but there is no request, unlock the mutex again.
Finally, refactor the trigger processing to make it more understandable.
Fixes carologistics/fawkes-robotino#368.

CX: avoid double mutex requests

---

src/libs/blackboard/net/handler.cpp
src/libs/blackboard/net/interface_listener.cpp
src/libs/blackboard/net/interface_listener.h
src/libs/blackboard/net/interface_proxy.cpp
src/libs/blackboard/net/interface_proxy.h
src/libs/blackboard/remote.cpp
src/libs/interface/interface.cpp
src/libs/interface/interface.h

Some of the remote blackboard code was not correctly adapted to deal with the change vs. refresh functionality introduced by PR #244. This commit should fix the resulting errors, in particular this one:
```
BlackBoardNetworkHandler: Unknown message of type 9 received
```

blackboard: fix data change handling over network

---

src/plugins/gazebo/node_thread.cpp

This PR fixes problems when using gazebo 10. The changes introduced should retain backwards compatibility (or at least the same managers and the same functions are present in all the other gazebo API versions i checked; i stopped at gazebo 4...).
I am a bit confused as of why we need to initialize topic and connection manager by hand, as it was not necessary when running an isolated small program subscribing to the same running gazebo server.

gazebo: explicitly start topic- and connection manager

---

src/libs/protobuf_clips/communicator.cpp
src/libs/protobuf_clips/communicator.h

Ported from https://github.com/robocup-logistics/rcll-refbox/pull/94.
Edit: In fawkes the `next_client_id_` member is already initialized in the constructors.

fix potentially inconsistent protobuf client ids

---

src/plugins/clips-executive/clips/coordination-mutex.clp

This PR fixes a small bug as the request when unlocking is `UNLOCK` not `LOCK`.

clips-executive: correctly process unlock request on reacquire

---

src/libs/core/tests/Makefile
src/libs/core/tests/catch2_main.cpp
src/libs/core/tests/test_circular_buffer.cpp
src/libs/core/utils/circular_buffer.h
src/libs/syncpoint/syncpoint.cpp

If a pending emitter fails to emit, we may also be interested in when
the component emitted the last time. Print the time difference between
now and the last emit call.
This is especially helpful to understand whether a component is just a bit too slow (e.g., we waited for 0.4s) or its loop is stuck (with a wait time of several seconds).

Print syncpoint wait times

---

src/plugins/clips-executive/clips/domain.clp

Previously the recursive deletion could not work as the function
argument was assumed to be an atomic precondition name.
Also, the case of a resulting empty precondition was not covered.
While fixing the issues above it prove to be more convenient to actually
change the argument from a precondition name to a fact-id/address.

clips-executive: properly remove preconditions recursively

---

src/plugins/mongodb/mongodb_instance_config.cpp
src/plugins/mongodb/mongodb_instance_config.h

Using a tmp directory ensures that we always start with an empty
database, as we switch the database directory with every restart.

mongodb: add config option to store data and log in a tmp directory

---

src/plugins/gazebo/gazsim-laser/gazsim_laser_thread.cpp
src/plugins/gazebo/gazsim-robotino/gazsim_robotino_thread.cpp
src/plugins/gazebo/node_thread.cpp
src/plugins/gazebo/node_thread.h

Fix the gazebo client initialization:
* Call `gazebo::client::setup()`, following the [documentation](http://gazebosim.org/tutorials?tut=topics_subscribed&cat=transport)
* Remove TopicManager and ConnectionManager initializations. These work fine with a single robot, but often crash gazebo when used with multiple robots
* Publish a heartbeat, which somehow works around the issues with not receiving data
Also print topic names when we subscribe to them, for informational purposes.
I've tried debugging the subscription problems for a while, but it seems like some things are messed up either in gazebo-rcll or in gazebo itself. This workaround seems to work well enough for now.

Fix / work around gazebo client initialization issues

---

.buildkite/pipeline.yml

We have switched our build servers to CentOS 8, which works better with podman than docker.

Use podman instead of docker for buildkite builds

---

cfg/conf.d/clips-executive.yaml
src/plugins/clips-executive/clips/goal-tree.clp
src/plugins/clips-executive/clips/goals/run-parallel.clp
src/plugins/clips-executive/clips/test-scenario/domain.pddl
src/plugins/clips-executive/clips/test-scenario/goal-reasoner.clp
src/plugins/clips-executive/clips/test-scenario/goals/talk.clp
src/plugins/clips-executive/clips/test-scenario/plans/talk-plan.clp
src/plugins/clips-executive/clips/test-scenario/print-action.clp

This PR introduces a `RUN-PARALLEL` compound goal:
The `RUN-PARALLEL` goal executes all its sub-goals in parallel, starting
by selecting the ones with highest priority. Once those are `DISPATCHED`,
the next batch is selected.
So priorities can be used to give a head start to certain goals, e.g., to
acquire resources before other goals start or to serialize expensive expansion
tasks.
A run-parallel stops `SELECTING` goals once a sub-goal is `REJECTED` or
`FAILED`, unless it is configured to continue regardless (which is done
by specifying the goal parameter `continue-on`).

cx: add compound goal to run sub-goals in parallel

---

src/plugins/clips-executive/clips/goals/run-all.clp
src/plugins/clips-executive/clips/goals/try-all.clp

This PR addresses an issue, where some compound goals (`run-all` and `try-all`) with finish conditions based on the outcome of sub-goals are getting stuck.
The problem is caused by a race between progressing the progression of the sub-goal from `EVALUATED` to `RETRACTED` and progressing the parent goal from `DISPATCHED` to `FINISHED`. The intended way to avoid this issue is to react on `RETRACTED` sub-goals instead of `EVALUATED` ones. For `run-all` and `try-all` goals this was not the case yet.
While fixing the issue i also noted, that the `try-all` goal does not wait for the release of the resources of its sub-goals either, which is now fixed as well to make it consistent with the behaviour of other compound goals.

CX: finish compound goals based on retracted sub-goals

---

src/plugins/realsense/Makefile
src/tools/laser_calibration/Makefile

I tried to build for old times sake after upgrading my laptop to Fedora 33. Due to PCL missing Fawkes would not build. This PR fixes it. Additionally it fixes a small oversight in the laser_calibration Makefile leading to unexpected output coloring.

Fix build on minimal Fedora install

---

.buildkite/pipeline.yml

This avoids issues with podman that asks which registry to use.

buildkite: explicitly use the container image from docker.io

---

src/plugins/skiller/exec_thread.cpp

The string needs to be quoted, otherwise lua treats it as an (invalid)
integer.

skiller: fix crash on reader-removed event

---

src/plugins/clips-executive/clips/plan.clp
src/plugins/clips-executive/clips/skills-actions.clp
src/plugins/clips-executive/clips/skills.clp
src/plugins/clips-executive/clips/test-scenario-pddl/test-domain.clp
src/plugins/clips-executive/clips/test-scenario/test-domain.clp

This PR adds the adaptions to the CX required to execute actions on different Skillers, e.g., remote Skillers for distributed agents.
The changes mostly do not affect existing agents that only use the default Skiller, the only required change is to `(assert (skiller-control))` once.

CX: add support for handling multiple Skillers

---

etc/scripts/mongodb_skillsim_lookup.py
src/plugins/execution-time-estimator-lookup/lookup_estimator.cpp

This PR augments the helper script of the lookup estimator to a function, where samples can be generated from a mixture of gaussian distributions.
Further, the lookup query is  relaxed such that argument parameters do not need to match exactly, instead it suffices if the reference entry in the collection contains a placeholder `.*`.
This is helpful in case a skill call may have a wide parameter value range that do not contribute to the execution time (e.g., grasping actions in the RCLL contain the place which could be any machine on the field).
However, the implementation is a workaround, as ideally the lookup entries should simply be evaluated as regular expressions. However, this would require MongoDB 4.2 (through the `$regexMatch` feature).

Improve lookup estimator usability

---

src/libs/blackboard/net/handler.cpp
src/libs/blackboard/net/interface_listener.cpp
src/libs/blackboard/net/interface_proxy.cpp
src/libs/utils/uuid.h
src/lua/skiller/fawkes/init.lua
src/plugins/clips-agent/clips_agent_thread.cpp
src/plugins/ros/skiller_thread.cpp
src/plugins/skiller-simulator/exec_thread.cpp
src/tools/skillgui/skillgui.cpp

When comparing the exclusive controller of the skiller with an interface, always explicitly compare strings. In particular:
* Remove any comparisons to ints, which was just broken
* Do not do an implicit conversion to UUID, as this may fail if the UUID is empty
Fixes #284

Fix UUID handling in skillgui and avoid direct UUID comparisons

---

src/plugins/clips-executive/clips/goal.clp

This PR extends goals through the option to register a custom templated fact as goal-meta, see the code comments for details:
https://github.com/fawkesrobotics/fawkes/blob/9605f045031d912637529e59ec5b0ac1fbcc9f23/src/plugins/clips-executive/clips/goal.clp#L171-L185
Also a slot `is-executable` is added which is useful for agents that formulate goals that are not to be executed right away. The slot is not used for the core features yet.
https://github.com/fawkesrobotics/fawkes/blob/9605f045031d912637529e59ec5b0ac1fbcc9f23/src/plugins/clips-executive/clips/goal.clp#L211-L214
Also the slot `verbosity` is extended by a value `NOISY`

CX: add custom goal meta to goals

---

src/libs/utils/ipc/shm_registry.h

Tools like `fvshmem` and the `webview` plugin were unable to receive lists of actual SharedMemoryImageBuffers.
The `MAGIC_TOKEN_SIZE` defines the length of the character array `FIREVISION_SHM_IMAGE_MAGIC_TOKEN` which in turn is used to locate the respective shared memory buffers. However the length of 16 renders the actual string `FireVision Image` to be cropped by its null termination.
I have set a value of 32 to allow further extension of the name or adding other shared memory buffers.

Fix finding of shared memory buffers

---

etc/buildsys/rules.mk

If we are in the submodule's topdir, we should use the format target for
the root directory, not the sub-directory format target. This should be
done not only in TOP_BASEDIR (e.g.,  fawkes-robotino), but also if we
are in the submodule BASEDIR (i.e., fawkes-robotino/fawkes).

buildsys: fix erroneous override of format targets in submodule topdir

---

.lgtm/cpp-queries/resource-not-released.ql

The CodeQL query engine on lgtm.com no longer allows importing query-internal libraries such as `Critical.NewDelete`. This means that the customized query used by the Fawkes project cannot run. To fix it, I've copied the contents of the current version of the library into the query.

Make custom query work on LGTM again

---

src/plugins/gazebo/gazsim-comm/Makefile

We already check that we have it available, but we also need to use its
compile and link flags.
This fixes an abort due to an undefined symbol.

gazsim-comm: link against protobuf_comm

---

src/libs/pddl_parser/pddl_exception.h
src/libs/pddl_parser/pddl_parser.cpp

The issue https://github.com/fawkesrobotics/fawkes/issues/297 revealed that the error messages of the new pddl-parser are not working as intended.
This PR fixes this issue. The actual problem of https://github.com/fawkesrobotics/fawkes/issues/297 is that the respective domain.pddl contains errors which are hard to spot when the error messages are not displayed...

pddl-parser: collapse exception msg before rethrowing

---

src/plugins/clips-executive/clips/domain.clp

Otherwise this rule would loop if an action has no precondition (which
is the case in the test scenarios).

clips-executive: only ground precondition if formula exists

---

src/plugins/clips-executive/clips/domain.clp

Executability check for plan-actions did not necessarily rely on the entire precondition formula to be satisfied. This is fixed here.

Fix plan-action executability check

---

.buildkite/pipeline.yml

The old plugin is no longer available, switch to the podman plugin provided by
https://github.com/compono/podman-buildkite-plugin.

Switch the buildkite podman plugin to supported plugin

---

src/plugins/clips-executive/clips/goal.clp

Currently, this rule fires even when you already have a goal meta,
because the goal fact does not change and hence the test is not
re-evaluated.

clips-executive: fix broken default goal meta assertion

---

src/plugins/clips-executive/rest-api/clips-executive-rest-api.cpp

Webview frontend tried to access preconditions of actions even if they don't exist. Add a check to prevent this.

Webview: prevent segfault by checking if preconditions are empty

---

src/plugins/pddl-planner/pddl-planner_thread.cpp
src/plugins/pddl-planner/pddl-planner_thread.h

Call the PDDL planner POPF and parse its result. Use std::regex to parse
the result to get rid of the action timestamps, which we currently do
not use.

pddl-planner: add support for POPF

---

src/plugins/clips-executive/clips/resource-locks.clp

This PR addresses an issue that arises, when multiple goals have overlapping required resources.
In particular, one must take care when rejecting and cleaning up goals in that scenario, so that all COMMITTED goals are properly processed.
A problem this PR fixes follows the following pattern:
1. Goal A and B are `COMMITTED`, both require resource R
2. A requests resource R and asserts corrsponding `resource-request`
3. Request of A fails
4. B reacts on failed lock-request of A, gets rejected and cleans up mutex of R (despite not being the issuer of the `resource-request`)
5. A still has not processed the request, therefore it gets stuck

fix resource locks interfering with different goals

---

src/libs/syncpoint/syncpoint.cpp

This helps reducing the spam in the output during regular execution, while still allowing to debug potential problems.

syncpoint: log synpoint warnings to debug

---

src/plugins/clips-pddl-parser/effect_visitor.cpp
src/plugins/clips-pddl-parser/precondition_visitor.cpp

As we do not actually have support for durative actions yet, ignore the
temporal aspects of the action's preconditions and effects, and instead
just parse them the same way as primitive actions. In particular, this
means that we ignore the temporal operators 'at start', 'over all', and
'at end'.

clips-pddl-parser: add primitive support for durative actions

---

.buildkite/steps.d/20-webview-frontend.yml

For the main build, we switched to a different plugin a while ago. Also
switch to the new plugin for the webview build.
This fixes the build failure that occurred after merging #324:
https://buildkite.com/fawkesrobotics/fawkes-build/builds/1788#2009cbba-dca9-495d-bb28-67f286df8cec

buildkite: also use new podman plugin for webview builds

---

src/libs/protobuf_clips/communicator.cpp

The `pb-has-field` sometimes returned 0 instead of FALSE. Also, there was an unnecessary case distinction between optional and required fields. In both cases one can simple check if the field is set.

protobuf_clips: return clips value FALSE if field is not set

---

cfg/conf.d/clips-executive.yaml
cfg/conf.d/meta_plugins.yaml
src/plugins/clips-executive/clips/test-scenario/worldmodel-facts.clp
src/plugins/clips-executive/clips/wm-template-facts.clp
src/plugins/clips-executive/clips/worldmodel.clp

This PR adds functions to build wm-fact keys from templated facts, as well as converting those wm-fact keys back to those facts.
A showcase is provided for the test-scenario, where goal facts are continually synced to wm-facts.
This can be used to put templated facts in the robot-memory backend.

cx: add support to translate between template facts and wm-facts

---

cfg/conf.d/realsense2.yaml
src/plugins/realsense2/Makefile
src/plugins/realsense2/realsense2_thread.cpp
src/plugins/realsense2/realsense2_thread.h

This PR creates a shared memory buffer for the rgb images from the realsense and allows to save images.
Important details:
- The visual servoing approach requires these commits for its object detector to work.
- Visual servoing is unstable when using the save_images feature and will often drive into MPS's. If images should be captured while using visual servoing, save them in the object-tracking plugin.

realsense: Switch from point cloud and to only rgb

---

src/plugins/clips-executive/clips/test-scenario/worldmodel-facts.clp
src/plugins/clips-executive/clips/wm-template-facts.clp
src/plugins/clips-executive/clips/worldmodel.clp

This PR is a followup to https://github.com/fawkesrobotics/fawkes/pull/329. When actively using the features introduced there, i realized that the enoding of wm-facts representing templates was slightly off.
Essentially, the wm-key should only contribute template slots that determine the uniqueness of facts from that template.
Other slots can simply be stored in the `values` field.
I also stumbled accross some minor bugs and imroved the code a bit. I leave this as a draft PR for a bit to test this feature more actively in the coming days.

cx: world model template fact rework

---

src/plugins/clips-executive/rest-api/clips-executive-rest-api.cpp

If a precondition fact for a plan-action might not exist (e.g. when only a partial view of the world-model is restored), the rest-api
can cause segfaults, as it tries to access a fact that does not exist. To prevent this, the existence of the precondition fact is checked first.

REST-API: catch non-existing precondition fact pointers

---

.buildkite/pipeline.yml
src/libs/core/tests/test_wait_condition.cpp
src/libs/syncpoint/tests/test_syncpoint.cpp
src/plugins/navgraph/rospub_thread.cpp

Update buildkite to Fedora 35 and fix some remaining build issues that have not been fixed in #324.
Also switch to the new builder image in https://github.com/fawkesrobotics/docker-fawkes-builder. The old one consisted of three images built on top of each other, this one is built from scratch and makes it easier to maintain. The new images uses the same image registry, but a different tag naming scheme.

Update to Fedora 35

---

src/plugins/clips-robot-memory/clips_rm_trigger.cpp
src/plugins/clips-ros/clips_ros_thread.cpp
src/plugins/clips/aspect/clips_env_manager.cpp
src/plugins/clips/feature_redefine_warning.cpp
src/plugins/clips/rest-api/clips-rest-api.cpp
src/plugins/hardware-models/hardware_models_thread.cpp

This PR addresses smaller changes necessary in order to utilize the updated clips and clipsmm packages from https://copr.fedorainfracloud.org/coprs/thofmann/clips-6.31.
Also, as the function `set_slot` is more strict in newer versions when it comes to type restrictions and the intended usage (building facts that do not exist in working memory as opposed to modifying existing facts), this PR adds some sanity checks across to detect potential misuse.

Switch to most recent clips 6.3 update

---

src/plugins/bbsync/sync_listener.cpp

When unregistering the sync listener for the first time, the bbil_maps
of it are cleared and an update is necessary to fill them again before
unregistering it again. Otherwise, the notifier of the second blackboard
is not properly unregistering the listener.

Properly clean up writer notifier when destructing a SyncInterface

---

.buildkite/pipeline.yml

This PR relies on carologistics/fawkes-robotino#583 which, among other things, uses speed up simulation for speed tests.
Buildtests will run in under 15 minutes testing a pre-configured test-game for both the central and decentral agent. Thus a timeout of 20 minutes should be sufficient to detect failing/stuck tests.

Reduce timeout for buildtests

---

cfg/conf.d/laser-lines.yaml
src/plugins/laser-lines/laser-lines-thread.cpp
src/plugins/laser-lines/laser-lines-thread.h
src/plugins/laser-lines/line_info.cpp
src/plugins/laser-lines/line_info.h

This adds raw laserlines transformed to a custom frame (i.e. "map") to
ease accessibility for Fawkes instances connected via bbsync rather than
having to synchronize all transforms.
---------------
Marked as draft until Linter issues in F35 are handled.

Add transformable laserlines

---

cmake/dependencies.cmake

Some packages that are currently not ported over to cmake require the boost::chrono lib.

cmake: added boost::chrono lib to cmake

---

cfg/conf.d/realsense2.yaml
src/plugins/realsense2/realsense2_thread.cpp
src/plugins/realsense2/realsense2_thread.h

This enables the realsense plugin to use a certain camera based on a serial number parameter. If several cameras are connected, one can now choose which one to use.

realsense2: fix for more than one camera

---

src/plugins/clips-executive/clips/skills-actions.clp

If the status of a skiller interface is inactive while an action is supposed to be running on the same interface it was never
executed, failed, or was aborted. Therefore fail the action in such cases.

cx: fail action if skiller interface inactive during runtime

---

Dockerfile
src/plugins/clips-executive/clips/action-selection/sequential.clp
src/plugins/clips-executive/clips/action-selection/temporal.clp
src/plugins/clips-executive/clips/plan.clp

Some applications of the CX might want to suspend plans during their execution. Here we add two slots to the plan fact template which allows users to implement such suspension mechanisms.

CX: Add slots to control suspension of plans

---

src/plugins/robotino/sensor_thread.cpp
src/plugins/ros2/CMakeLists.txt
src/plugins/ros2/irscan_plugin.cpp
src/plugins/ros2/irscan_thread.cpp
src/plugins/ros2/irscan_thread.h

Now publishing the IR_sensor distances to ros2 with the ros2-irscan plugin.
Fixed the conversion of the distances to meters.

ir_sensor: added ros2 support for the IR_sensors

---

cfg/conf.d/execution-time-estimator.yaml
src/libs/execution_time_estimator/execution_time_estimator.cpp
src/libs/execution_time_estimator/execution_time_estimator.h
src/libs/navgraph/navgraph_node.h
src/plugins/execution-time-estimator-lookup/lookup_estimator.cpp
src/plugins/execution-time-estimator-lookup/lookup_estimator.h
src/plugins/execution-time-estimator-navgraph/execution_time_estimator_navgraph_thread.cpp
src/plugins/execution-time-estimator-navgraph/navgraph_estimator.cpp
src/plugins/execution-time-estimator-navgraph/navgraph_estimator.h
src/plugins/skiller-simulator/exec_thread.cpp
src/plugins/skiller-simulator/exec_thread.h

This PR extends the execution-time-estimator-navgraph feature to consider navgraph paths instead of straight-line distances. Additionally, the plugin may act as writer to a Position3DInterface to update the Pose along the way, if configured.
This required changes to the execution-time-estimator interface, as the estimator now also needs to be notified when the skill simulation starts, not only when it ends.

add optional pose update to navgraph exec-time estimator

---

src/plugins/clips-executive/clips/domain.clp

It operated on retracted facts

clips-executive: fix crashes of remove-precond function

---

cfg/conf.d/meta_plugins.yaml
src/lua/skiller/fawkes/init.lua
src/plugins/ros2/CMakeLists.txt
src/plugins/ros2/aspect/ros2.cpp
src/plugins/ros2/aspect/ros2.h
src/plugins/ros2/aspect/ros2_inifin.cpp
src/plugins/ros2/aspect/ros2_inifin.h
src/plugins/ros2/cx_skiller_plugin.cpp
src/plugins/ros2/cx_skiller_thread.cpp
src/plugins/ros2/cx_skiller_thread.h
src/plugins/ros2/node_thread.cpp
src/plugins/ros2/node_thread.h
src/plugins/ros2/skill_node.cpp
src/plugins/ros2/skill_node.h

This PR integrates a [ROS 2 CLIPS-Executive](https://github.com/fawkesrobotics/ros2-clips-executive) executor feature, such that one can write reasoning agents using the ROS 2 CX while using the fawkes skiller as executor.

Add skiller executor feature for ROS 2 CLIPS-Executive

---

src/plugins/clips-executive/clips/resource-locks.clp

The only problematic case that should not be cleaned up is when a mutex
has a pending or acquired response (as then we would need for a trigger). This is
already excluded through the precondition.
In particular, now the rule can clean up mutexes with request LOCK and
response NONE (which therefore did not try to lock asynchronously yet).
The problem can be nicely seen in this log snippet, where first all resource-requests are created, then an immediate response from resource PROMISE-C-RS2-OUTPUT causes the fast rejection to trigger while all other mutexes have request LOCK and response NONE:
```
D 01:21:44.356736 CLIPS (executive): FIRE  813 resource-locks-request-lock: f-43741,*,*,*
W 01:21:44.356750 CLIPS (executive): Locking resource PROMISE-C-RS2-INPUT       
D 01:21:44.356778 CLIPS …
```

clips-executive: Properly clean up mutex responses and requests on fast reject

---

src/plugins/ros2/navigator_thread.cpp

The goal handles sometimes cause a goal handle id mismatch this is now handled by sending the target again.

ros2-navigator: goal handle fixed

---

Dockerfile
src/libs/syncpoint/tests/test_syncpoint.cpp
src/plugins/clips-pddl-parser/precondition_visitor.cpp
src/plugins/rrd/CMakeLists.txt
src/plugins/rrd/rrd_thread.cpp

There is an issue with rrdtool-devel, which has a changed interface despite not having a version change (at least according to pkg-config, dnf actually shows that it was bumped a few times in f40).
This causes incompatibilities with f39, hence I opted to disable the plugin for now, despite the fixes supplied here.

switch to f40

---

src/plugins/clips-executive/clips/domain.clp

This PR allows for more targeted cleanup of grounded pddl formulas.
Currently, all formulas get removed whenever one formula should be, which triggers a mass re-grounding of formulas. Depending on the number of grounded formulas, this can be quite expensive.
Hence, avoid this by actually only cleaning up groundings when needed.
Note that this can have side effects as potentially some pddl-groundings could dangle without ever being cleaned up (e.g., if a plan action is formulated but removed again before being executed).
Hence it is advisable to clean up pddl-groundings manually (or periodically).

better grounding cleanup

---

cmake/ros2.cmake

Do not build with ROS 2 support if these checks fail, because it will cause problems.

cmake: properly check for ROS_DISTO and base install dir

---

src/plugins/realsense2/realsense2_thread.cpp
src/plugins/realsense2/realsense2_thread.h
src/plugins/ros2/motorinterface_thread.cpp
src/plugins/ros2/navigator_thread.cpp
src/plugins/ros2/navigator_thread.h

This PR fixes some crucial performance issues:
1. the ros2 motor interface was needlessly polling in the unused loop function, maxing out a thread
2. the realsense2 thread is generally quite slow and causes the desired loop time to constantly be crossed. Instead, put it in a separate thread at a more realistic rate.
3. Not really an issue, but the ros2 navigator on the other hand should probably be part of the managed loop hooks, as it can easily keep the desired loop rates. This gets rid of the arbitrary usleep function.
~TODOs:~
- ~test more on real robots~
- ~make realsense2 update rate a config value~

various speedup
